version: '3.8'

services:
  backend:
    container_name: django
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: vuetify
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/blnk:/app/frontend/blnk
    working_dir: /app/frontend/blnk

  db:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blnk
      - POSTGRES_USER=elsaeed
      - POSTGRES_PASSWORD=12345

volumes:
  pgdata:





